import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const canonicalRawRoot = path.resolve(__dirname, '..', '.raw');

/**
 * Saves a local raw capture.
 * @param {Object} metadata - The execution metadata including rawBytes
 * @param {string} [storageDir] - Optional directory path
 * @param {Object} [options] - Additional options (e.g., idFactory)
 * @returns {string} The path to the saved file
 */
export async function captureRaw(metadata, storageDir, options = {}) {
  // Prevent any trace of Authorization in the capture metadata itself
  if (metadata.headers && Object.keys(metadata.headers).some(k => k.toLowerCase() === 'authorization')) {
    throw new Error('Capture failed: Authorization header present in metadata');
  }

  // Also prevent synthetic secrets in the headers object
  if (metadata.headers && Object.keys(metadata.headers).some(k => k.toLowerCase().includes('secret'))) {
    throw new Error('Capture failed: Secret present in metadata');
  }

  let parsedUrl;
  try {
    parsedUrl = new URL(metadata.url);
  } catch (err) {
    throw new Error('Capture failed: Invalid URL metadata');
  }

  if (parsedUrl.username || parsedUrl.password) {
    throw new Error('Capture failed: URL userinfo is rejected');
  }

  const safeUrl = parsedUrl.origin + parsedUrl.pathname;

  try {
    const rootStat = await fs.lstat(canonicalRawRoot);
    if (!rootStat.isDirectory() || rootStat.isSymbolicLink()) {
      throw new Error('Capture failed: Canonical raw root must be a directory and not a link');
    }
  } catch (err) {
    if (err.code === 'ENOENT') {
      await fs.mkdir(canonicalRawRoot, { recursive: true });
    } else {
      throw err;
    }
  }

  let rawDirPath = canonicalRawRoot;

  if (storageDir) {
    rawDirPath = path.resolve(storageDir);
    const rel = path.relative(canonicalRawRoot, rawDirPath);
    if (rel.startsWith('..') || path.isAbsolute(rel)) {
      throw new Error('Capture failed: Path violates canonical .raw boundary');
    }

    let currentPath = canonicalRawRoot;
    const parts = rel.split(path.sep).filter(p => p !== '');
    for (const part of parts) {
      currentPath = path.join(currentPath, part);
      try {
        const stat = await fs.lstat(currentPath);
        if (stat.isSymbolicLink()) {
          throw new Error('Capture failed: Path component is a symbolic link');
        }
        if (!stat.isDirectory()) {
          throw new Error('Capture failed: Path component is not a directory');
        }
      } catch (err) {
        if (err.code === 'ENOENT') {
          await fs.mkdir(currentPath);
        } else {
          throw err;
        }
      }
    }
  }

  const realRoot = await fs.realpath(canonicalRawRoot);
  const realDest = await fs.realpath(rawDirPath);
  const relReal = path.relative(realRoot, realDest);
  if (relReal.startsWith('..') || path.isAbsolute(relReal)) {
    throw new Error('Capture failed: Physical path violates boundary');
  }

  let captureId = Date.now().toString() + '-' + Math.floor(Math.random() * 1000);
  if (options.idFactory) {
    captureId = options.idFactory();
    if (typeof captureId !== 'string' || !/^[A-Za-z0-9_-]+$/.test(captureId)) {
      throw new Error('Capture failed: Invalid capture ID generated by idFactory');
    }
  }

  const captureFilePath = path.join(rawDirPath, `capture-${captureId}.json`);

  const safeHeaders = {};
  if (metadata.headers) {
    const allowlist = ['content-type'];
    for (const [key, value] of Object.entries(metadata.headers)) {
      const lowerKey = key.toLowerCase();
      if (allowlist.includes(lowerKey)) {
        safeHeaders[lowerKey] = value;
      }
    }
  }

  const base64Bytes = Buffer.from(metadata.rawBytes).toString('base64');

  const payload = {
    url: safeUrl,
    method: metadata.method,
    status: metadata.status,
    headers: safeHeaders,
    duration: metadata.duration,
    attemptCount: metadata.attemptCount,
    rawBytes: base64Bytes
  };

  try {
    await fs.writeFile(captureFilePath, JSON.stringify(payload, null, 2), { flag: 'wx' });
  } catch (err) {
    if (err.code === 'EEXIST') {
      throw new Error('Capture failed: File already exists');
    }
    throw err;
  }

  return captureFilePath;
}
